# fly.toml app configuration file generated for fragrant-sun-1837 on 2023-10-18T19:03:30+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fragrant-sun-1837"
primary_region = "atl"

[build]

[env]
  HOST = "https://fragrant-sun-1837.fly.dev"
  PORT = "8081"
  SCOPES = "write_products,read_content,write_content"
  SHOPIFY_API_KEY = "64c5d7f017e8f83c27045aca4074895c"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
