# fly.toml app configuration file generated for throbbing-moon-9283 on 2023-10-19T11:11:39+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "throbbing-moon-9283"
primary_region = "ams"

[env]
  PORT = "8081"
  HOST = "https://throbbing-moon-9283.fly.dev"
  SHOPIFY_API_KEY = "64c5d7f017e8f83c27045aca4074895c"
  SCOPES = "write_products,read_content,write_content"

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
