# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "node-testing-app"
client_id = "bbf9e45efe27ce34e8ef0df50d243138"
application_url = "https://gaps-class-posters-mad.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content,write_content"

[auth]
redirect_urls = [
  "https://gaps-class-posters-mad.trycloudflare.com/auth/callback",
  "https://gaps-class-posters-mad.trycloudflare.com/auth/shopify/callback",
  "https://gaps-class-posters-mad.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-48abbc9b.myshopify.com"
